# Generated by Django 5.1.1 on 2025-03-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_user_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
