# Generated by Django 5.1.1 on 2025-03-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_user_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uniqueid',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
