# Generated by Django 5.1.1 on 2025-03-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_transaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True),
        ),
    ]
