# Generated by Django 5.1.1 on 2025-03-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_knowledgebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_bill_split',
            field=models.BooleanField(default=False),
        ),
    ]
